### ISSUE TITLE
invalid Unicode escape (ArgumentError) when sharing a cookbook

### ISSUE THREAD

**Issue by dougireton** [chef/knife-supermarket#14]
I'm getting this error on Windows 8.1 with ChefDK 0.5.1:

## Repo Steps
1. chef generate cookbook my_cookbook
1. knife supermarket share my_cookbook -VV

```batch
INFO: Using configuration from C:/Users/doug/.chef/knife.rb
DEBUG: No chefignore file found at c:\users\doug\chef/chefignore no files will be ignored
INFO: Validating ruby files
C:/opscode/chefdk/embedded/apps/chef/lib/chef/cookbook/syntax_check.rb:113:in `block in remove_uninteresting_ruby_files': invalid Unicode escape (Argu
mentError)
        from C:/opscode/chefdk/embedded/apps/chef/lib/chef/cookbook/syntax_check.rb:113:in `reject'
        from C:/opscode/chefdk/embedded/apps/chef/lib/chef/cookbook/syntax_check.rb:113:in `remove_uninteresting_ruby_files'
        from C:/opscode/chefdk/embedded/apps/chef/lib/chef/cookbook/syntax_check.rb:120:in `ruby_files'
        from C:/opscode/chefdk/embedded/apps/chef/lib/chef/cookbook/syntax_check.rb:125:in `untested_ruby_files'
        from C:/opscode/chefdk/embedded/apps/chef/lib/chef/cookbook/syntax_check.rb:159:in `validate_ruby_files'
        from C:/opscode/chefdk/embedded/apps/chef/lib/chef/cookbook_uploader.rb:143:in `block in validate_cookbooks'
        from C:/opscode/chefdk/embedded/apps/chef/lib/chef/cookbook_uploader.rb:140:in `each'
        from C:/opscode/chefdk/embedded/apps/chef/lib/chef/cookbook_uploader.rb:140:in `validate_cookbooks'
        from C:/opscode/chefdk/embedded/apps/chef/lib/chef/knife/cookbook_site_share.rb:71:in `run'
        from C:/Users/xgjo/.chefdk/gem/ruby/2.1.0/gems/knife-supermarket-0.2.1/lib/chef/knife/supermarket_share.rb:52:in `run'
        from C:/opscode/chefdk/embedded/apps/chef/lib/chef/knife.rb:422:in `block in run_with_pretty_exceptions'
        from C:/opscode/chefdk/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
        from C:/opscode/chefdk/embedded/apps/chef/lib/chef/knife.rb:421:in `run_with_pretty_exceptions'
        from C:/opscode/chefdk/embedded/apps/chef/lib/chef/knife.rb:214:in `run'
        from C:/opscode/chefdk/embedded/apps/chef/lib/chef/application/knife.rb:142:in `run'
        from C:/opscode/chefdk/embedded/apps/chef/bin/knife:25:in `<top (required)>'
        from C:/opscode/chefdk/bin/knife:63:in `load'
        from C:/opscode/chefdk/bin/knife:63:in `<main>'
```

Unfortunately, it doesn't point to where it thinks the Unicode escape error is.

**Comment by dougireton** [comment]
Seems like this is a duplicate of https://github.com/chef/chef-dk/issues/389
