### ISSUE TITLE
Error uploading cookbook (SSL_connect certificate verify failed)

### ISSUE THREAD

**Issue by MrWong99** [chef/knife-supermarket#17]
I followed the Tutorial <https://www.chef.io/blog/2015/04/21/setting-up-your-private-supermarket-server/> to create my personal supermarket. Everything worked fine until the part where you would share your cookbook. (I can reach the supermarket site via Browser and Login with my Chef User)
I downloaded a new starter kit from my server, fetched the ssl certificates and created a sample cookbook. After that I added the `knife[:supermarket_site] = 'https://supermarket.mycompany.com'` configuration to the `knife.rb` file. When I run the `knife supermarket share` command I get following result (Verbose output, WIN 8 Powershell):

``` shell
PS C:\Users\myuser\Desktop\chef-starter\chef-repo> knife supermarket share test "Other" -VV
INFO: Using configuration from C:/Users/myuser/Desktop/chef-starter/chef-repo/.chef/knife.rb
INFO: Validating ruby files
DEBUG: Ruby file C:\Users\myuser\Desktop\chef-starter\chef-repo\cookbooks\test/metadata.rb is unchanged, skipping syntax check
DEBUG: Ruby file C:\Users\myuser\Desktop\chef-starter\chef-repo\cookbooks\test/recipes/default.rb is unchanged, skipping syntax check
INFO: Validating templates
INFO: Syntax OK
DEBUG: Staging at C:/Users/myuser/AppData/Local/Temp/chef-test-build20151014-2436-1vdyth0
DEBUG: Staging C:\Users\myuser\Desktop\chef-starter\chef-repo\cookbooks\test\recipes\default.rb to C:/Users/myuser/AppData/Local/Temp/chef-test-build20151014-24361vdyth0/test/recipes/default.rb
DEBUG: Staging C:\Users\myuser\Desktop\chef-starter\chef-repo\cookbooks\test\.kitchen.yml to C:/Users/myuser/AppData/Local/Temp/chef-test-build20151014-2436-1vdyth0/test/.kitchen.yml
DEBUG: Staging C:\Users\myuser\Desktop\chef-starter\chef-repo\cookbooks\test\Berksfile to C:/Users/myuser/AppData/Local/Temp/chef-test-build20151014-2436-1vdyth0/test/Berksfile
DEBUG: Staging C:\Users\myuser\Desktop\chef-starter\chef-repo\cookbooks\test\chefignore to C:/Users/myuser/AppData/Local/Temp/chef-test-build20151014-2436-1vdyth0/test/chefignore
DEBUG: Staging C:\Users\myuser\Desktop\chef-starter\chef-repo\cookbooks\test\metadata.rb to C:/Users/myuser/AppData/Local/Temp/chef-test-build20151014-2436-1vdyth0/test/metadata.rb
DEBUG: Staging C:\Users\myuser\Desktop\chef-starter\chef-repo\cookbooks\test\README.md to C:/Users/myuser/AppData/Local/Temp/chef-test-build20151014-2436-1vdyth0/test/README.md
DEBUG: Generating metadata
Generating metadata for test from C:/Users/myuser/AppData/Local/Temp/chef-test-build20151014-2436-1vdyth0/test/metadata.rb
DEBUG: Generated C:/Users/myuser/AppData/Local/Temp/chef-test-build20151014-2436-1vdyth0/test/metadata.json
DEBUG: Temp cookbook directory is "C:/Users/myuser/AppData/Local/Temp/chef-test-build20151014-2436-1vdyth0"
Making tarball test.tgz
The command "which" could not be found.
DEBUG: Signing: method: post, path: /api/v1/cookbooks, file: #<File:0x6cf4050>, User-id: example, Timestamp: 2015-10-14T 09:45:28Z
ERROR: Error uploading cookbook test to the Opscode Cookbook Site: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed. Increase log verbosity (-VV) for more information.
DEBUG:
C:/opscode/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:920:in `connect'
C:/opscode/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:920:in `block in connect'
C:/opscode/chefdk/embedded/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
C:/opscode/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:920:in `connect'
C:/opscode/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
C:/opscode/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:852:in `start'
C:/opscode/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:1369:in `request'
C:/opscode/chefdk/embedded/apps/chef/lib/chef/cookbook_site_streaming_uploader.rb:149:in `make_request'
C:/opscode/chefdk/embedded/apps/chef/lib/chef/cookbook_site_streaming_uploader.rb:68:in `post'
C:/Users/myuser/.chefdk/gem/ruby/2.1.0/gems/knife-supermarket-0.2.1/lib/chef/knife/supermarket_share.rb:68:in `do_upload'
C:/opscode/chefdk/embedded/apps/chef/lib/chef/knife/cookbook_site_share.rb:92:in `run'
C:/Users/myuser/.chefdk/gem/ruby/2.1.0/gems/knife-supermarket-0.2.1/lib/chef/knife/supermarket_share.rb:52:in `run'
C:/opscode/chefdk/embedded/apps/chef/lib/chef/knife.rb:422:in `block in run_with_pretty_exceptions'
C:/opscode/chefdk/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
C:/opscode/chefdk/embedded/apps/chef/lib/chef/knife.rb:421:in `run_with_pretty_exceptions'
C:/opscode/chefdk/embedded/apps/chef/lib/chef/knife.rb:214:in `run'
C:/opscode/chefdk/embedded/apps/chef/lib/chef/application/knife.rb:142:in `run'
C:/opscode/chefdk/embedded/apps/chef/bin/knife:25:in `<top (required)>'
C:/opscode/chefdk/bin/knife:63:in `load'
C:/opscode/chefdk/bin/knife:63:in `<main>'
```

Note that the path variable only says `'/api/v1/cookbooks' (line: 21)` and does not contain my supermarket server url. When I change the knife.rb to point to `knife[:supermarket_site] = 'supermarket.mycompany.com'` the path variable changes to `'supermarket.mycompany.com/api/v1/cookbooks'` but I get another error:

``` shell
PS C:\Users\myuser\Desktop\chef-starter\chef-repo> knife supermarket share test "Other" -VV
INFO: Using configuration from C:/Users/myuser/Desktop/chef-starter/chef-repo/.chef/knife.rb
INFO: Validating ruby files
DEBUG: Ruby file C:\Users\myuser\Desktop\chef-starter\chef-repo\cookbooks\test/metadata.rb is unchanged, skipping syntax check
DEBUG: Ruby file C:\Users\myuser\Desktop\chef-starter\chef-repo\cookbooks\test/recipes/default.rb is unchanged, skipping syntax check
INFO: Validating templates
INFO: Syntax OK
DEBUG: Staging at C:/Users/myuser/AppData/Local/Temp/chef-test-build20151014-6040-1exe44s
DEBUG: Staging C:\Users\myuser\Desktop\chef-starter\chef-repo\cookbooks\test\recipes\default.rb to C:/Users/myuser/AppData/Local/Temp/chef-test-build20151014-6040-1exe44s/test/recipes/default.rb
DEBUG: Staging C:\Users\myuser\Desktop\chef-starter\chef-repo\cookbooks\test\.kitchen.yml to C:/Users/myuser/AppData/Local/Temp/chef-test-build20151014-6040-1exe44s/test/.kitchen.yml
DEBUG: Staging C:\Users\myuser\Desktop\chef-starter\chef-repo\cookbooks\test\Berksfile to C:/Users/myuser/AppData/Local/Temp/chef-test-build20151014-6040-1exe44s/test/Berksfile
DEBUG: Staging C:\Users\myuser\Desktop\chef-starter\chef-repo\cookbooks\test\chefignore to C:/Users/myuser/AppData/Local/Temp/chef-test-build20151014-6040-1exe44s/test/chefignore
DEBUG: Staging C:\Users\myuser\Desktop\chef-starter\chef-repo\cookbooks\test\metadata.rb to C:/Users/myuser/AppData/Local/Temp/chef-test-build20151014-6040-1exe44s/test/metadata.rb
DEBUG: Staging C:\Users\myuser\Desktop\chef-starter\chef-repo\cookbooks\test\README.md to C:/Users/myuser/AppData/Local/Temp/chef-test-build20151014-6040-1exe44s/test/README.md
DEBUG: Generating metadata
Generating metadata for test from C:/Users/myuser/AppData/Local/Temp/chef-test-build20151014-6040-1exe44s/test/metadata.rb
DEBUG: Generated C:/Users/myuser/AppData/Local/Temp/chef-test-build20151014-6040-1exe44s/test/metadata.json
DEBUG: Temp cookbook directory is "C:/Users/myuser/AppData/Local/Temp/chef-test-build20151014-6040-1exe44s"
Making tarball test.tgz
The command "which" could not be found.
DEBUG: Signing: method: post, path: supermarket.kisters.de/api/v1/cookbooks, file: #<File:0x6db3fa8>, User-id: example, Timestamp: 2015-10-14T10:02:49Z
ERROR: Error uploading cookbook test to the Opscode Cookbook Site: the scheme http does not accept registry part: :80 (or bad hostname?). Increase log verbosity (-VV) for more information.
DEBUG:
C:/opscode/chefdk/embedded/lib/ruby/2.1.0/uri/generic.rb:214:in `initialize'
C:/opscode/chefdk/embedded/lib/ruby/2.1.0/uri/http.rb:84:in `initialize'
C:/opscode/chefdk/embedded/lib/ruby/2.1.0/uri/common.rb:214:in `new'
C:/opscode/chefdk/embedded/lib/ruby/2.1.0/uri/common.rb:214:in `parse'
C:/opscode/chefdk/embedded/lib/ruby/2.1.0/uri/common.rb:747:in `parse'
C:/opscode/chefdk/embedded/lib/ruby/2.1.0/uri/common.rb:1232:in `URI'
C:/opscode/chefdk/embedded/apps/chef/lib/chef/monkey_patches/net_http.rb:55:in `proxy_uri'
C:/opscode/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:1016:in `proxy?'
C:/opscode/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:869:in `connect'
C:/opscode/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
C:/opscode/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:852:in `start'
C:/opscode/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:1369:in `request'
C:/opscode/chefdk/embedded/apps/chef/lib/chef/cookbook_site_streaming_uploader.rb:149:in `make_request'
C:/opscode/chefdk/embedded/apps/chef/lib/chef/cookbook_site_streaming_uploader.rb:68:in `post'
C:/Users/myuser/.chefdk/gem/ruby/2.1.0/gems/knife-supermarket-0.2.1/lib/chef/knife/supermarket_share.rb:68:in `do_upload'
C:/opscode/chefdk/embedded/apps/chef/lib/chef/knife/cookbook_site_share.rb:92:in `run'
C:/Users/myuser/.chefdk/gem/ruby/2.1.0/gems/knife-supermarket-0.2.1/lib/chef/knife/supermarket_share.rb:52:in `run'
C:/opscode/chefdk/embedded/apps/chef/lib/chef/knife.rb:422:in `block in run_with_pretty_exceptions'
C:/opscode/chefdk/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
C:/opscode/chefdk/embedded/apps/chef/lib/chef/knife.rb:421:in `run_with_pretty_exceptions'
C:/opscode/chefdk/embedded/apps/chef/lib/chef/knife.rb:214:in `run'
C:/opscode/chefdk/embedded/apps/chef/lib/chef/application/knife.rb:142:in `run'
C:/opscode/chefdk/embedded/apps/chef/bin/knife:25:in `<top (required)>'
C:/opscode/chefdk/bin/knife:63:in `load'
C:/opscode/chefdk/bin/knife:63:in `<main>'
```

I would really appreciate any help and thanks in advance!

**Comment by MrWong99** [comment]
Found the error: https://gist.github.com/luislavena/f064211759ee0f806c88
